services:
  api:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - .env